### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by MatteoAndriolo** [MatteoAndriolo/TSP_Optimization_Solver#44]
- [ ] Greedy heuristic with GRASP
- [ ] Extra-mileage heuristic (1pt)
- [ ] 2-OPT refining heuristic
- [ ] Metaheuristics: Tabu Search
- [ ] Metaheuristics: VNS
- [ ] Simulated Annealing (1pt)
- [ ] Genetic Algorithm (1pt)
- [ ] Basic TSP model in CPLEX (without SECs)
- [ ] Benders' "loop" method with SEC separation for integer solutions
- [ ] Patching heuristic (1pt)
- [ ] Branch-and-Cut implementation in CPLEX through callbacks
- [ ] Posting heuristic solutions and adding user cuts for fractional solutions (1pt)
- [ ] Matheuristics: hard fixing
- [ ] Matheuristics: local branching
- [ ] Extensive use of performance profile plots for algorithm comparison (1pt)
- [ ] Writing style
